### ISSUE TITLE
捕获异常的业务处理过程矛盾

### ISSUE THREAD

**Issue by Anoxia** [top-think/think#505]
TP的异常处理依赖think\Lang和think\Config，根据TP系统加载流程首先使用Config加载配置数据，然后其他业务在配置数据的基础上执行，当think\Config类的set方法发生异常时时无法被正确捕获并显示，代码如下：
```php
public static function set($name, $value = null, $range = '')
    {
        $range = $range ?: self::$range;
        func_test($range);
```
调用一个不存在的函数，抛出的异常是：
```php

Fatal error: Uncaught think\exception\ErrorException: array_change_key_case() expects parameter 1 to be array, null given in /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php:46 Stack trace: #0 [internal function]: think\Error::appError(2, 'array_change_ke...', '/Users/Anoxia/D...', 46, Array) #1 /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php(46): array_change_key_case(NULL) #2 /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php(125): think\Cookie::init() #3 /Users/Anoxia/Documents/Study/impress/core/library/think/Lang.php(161): think\Cookie::get('think_var') #4 /Users/Anoxia/Documents/Study/impress/core/library/think/exception/Handle.php(212): think\Lang::detect() #5 /Users/Anoxia/Documents/Study/impress/core/library/think/exception/Handle.php(43): think\exception\Handle->getMessage(Object(think\exception\ThrowableError)) #6 /Users/Anoxia/Documents/Study/impress/core/library/think/Error.php(43): think\exception\Handle->report(Object(think\exception\ThrowableError)) # in /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php on line 46

Fatal error: Uncaught think\exception\ErrorException: array_change_key_case() expects parameter 1 to be array, null given in /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php:46 Stack trace: #0 [internal function]: think\Error::appError(2, 'array_change_ke...', '/Users/Anoxia/D...', 46, Array) #1 /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php(46): array_change_key_case(NULL) #2 /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php(125): think\Cookie::init() #3 /Users/Anoxia/Documents/Study/impress/core/library/think/Lang.php(161): think\Cookie::get('think_var') #4 /Users/Anoxia/Documents/Study/impress/core/library/think/exception/Handle.php(212): think\Lang::detect() #5 /Users/Anoxia/Documents/Study/impress/core/library/think/exception/Handle.php(43): think\exception\Handle->getMessage(Object(think\exception\ErrorException)) #6 /Users/Anoxia/Documents/Study/impress/core/library/think/Error.php(43): think\exception\Handle->report(Object(think\exception\ErrorException)) # in /Users/Anoxia/Documents/Study/impress/core/library/think/Cookie.php on line 46
```
其原因是由于think\Config出错，配置未被正常加载导致think\Lang的detect方法以及think\Cookie的init方法读取的配置数据为空。

**Comment by liu21st** [comment]
可是实际开发中 config类发生异常的可能性并不大吧 不像缓存之类的

**Comment by Anoxia** [comment]
@liu21st ，好吧，
